name=MebRenk
version=1.0.0
author=ismetelk-coder
maintainer=ismetelk-coder
sentence=TCS34725 Renk Sensörü Kütüphanesi - Arduino için
paragraph=MEb Robot Yumurta Toplama Kategorisi için renk sınıflandırması yapan Arduino kütüphanesi. Otomatik kalibrasyonu ve hassas renk tespiti sunur.
category=Sensors
url=https://github.com/ismetelk-coder/Meb_Renk
architectures=avr,arm
includes=MebRenk.h
